limit.maxIDLength:
  - value: 255
    constraints: {}
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
    # Development setup only. Do not enable this in production.
    constraints: {}
